//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.04 at 10:00:40 PM CAT 
//


package org.mthu.shortestpath;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mthu.shortestpath package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ShortestPathServiceRequest_QNAME = new QName("http://www.mthu.org/ShortestPath", "ShortestPathServiceRequest");
    private final static QName _ShortestPathServiceResponse_QNAME = new QName("http://www.mthu.org/ShortestPath", "ShortestPathServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mthu.shortestpath
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShortestPathServiceResponse }
     * 
     */
    public ShortestPathServiceResponse createShortestPathServiceResponse() {
        return new ShortestPathServiceResponse();
    }

    /**
     * Create an instance of {@link ShortestPathServiceRequest }
     * 
     */
    public ShortestPathServiceRequest createShortestPathServiceRequest() {
        return new ShortestPathServiceRequest();
    }

    /**
     * Create an instance of {@link Planet }
     * 
     */
    public Planet createPlanet() {
        return new Planet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShortestPathServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mthu.org/ShortestPath", name = "ShortestPathServiceRequest")
    public JAXBElement<ShortestPathServiceRequest> createShortestPathServiceRequest(ShortestPathServiceRequest value) {
        return new JAXBElement<ShortestPathServiceRequest>(_ShortestPathServiceRequest_QNAME, ShortestPathServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShortestPathServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mthu.org/ShortestPath", name = "ShortestPathServiceResponse")
    public JAXBElement<ShortestPathServiceResponse> createShortestPathServiceResponse(ShortestPathServiceResponse value) {
        return new JAXBElement<ShortestPathServiceResponse>(_ShortestPathServiceResponse_QNAME, ShortestPathServiceResponse.class, null, value);
    }

}
